### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [wireapp/cryptobox-c#6]
I would like to point out that an identifier like "[`__CRYPTOBOX_H__`](https://github.com/wireapp/cryptobox-c/blob/fde2cc4fc3c0116666ed2b74c89e0c82705af4a6/src/cbox.h#L16)" [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by twittner** [comment]
Thank you. The include guard has been modified.

**Comment by elfring** [comment]
Thanks for [your improvement of an affected include guard](https://github.com/wireapp/cryptobox-c/commit/fe677228f26961b625b463befe8738c33121019a "Deletion of a few underscores").
